const API = 'http://localhost:3000/api';
const content = document.querySelector('#content');
const titles = { dashboard: 'Dashboard', entrada: 'Registrar entrada', salida: 'Registrar salida', espacios: 'Espacios de estacionamiento', estadias: 'Historial de estadías', clientes: 'Clientes', vehiculos: 'Vehículos', pagos: 'Pagos registrados', reportes: 'Reportes SQL' };
const money = value => new Intl.NumberFormat('es-HN', { style: 'currency', currency: 'HNL' }).format(Number(value || 0));
const date = value => value ? new Intl.DateTimeFormat('es-HN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—';
const escape = value => String(value ?? '—').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[char]);
const get = async path => { const response = await fetch(`${API}${path}`); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'No se pudo consultar la base de datos.'); return data; };
const notice = (message, type = 'success') => { const el = document.querySelector('#notice'); el.className = type; el.textContent = message; el.style.display = 'block'; window.scrollTo({ top: 0, behavior: 'smooth' }); };
const table = (headers, rows) => rows.length ? `<div class="table-wrap"><table><thead><tr>${headers.map(h => `<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>` : '<p class="empty">No hay registros para mostrar.</p>';
const badge = status => `<span class="badge ${escape(status)}">${escape(status)}</span>`;

async function dashboard() { const d = await get('/dashboard'); const r = d.resumen; content.innerHTML = `<div class="stats"><div class="card"><span>Total de espacios</span><b>${r.total_espacios}</b></div><div class="card"><span>Espacios ocupados</span><b>${r.ocupados}</b></div><div class="card"><span>Espacios disponibles</span><b>${r.disponibles}</b></div><div class="card"><span>Ocupación</span><b>${r.porcentaje_ocupacion || 0}%</b></div><div class="card"><span>Ingresos totales</span><b class="money">${money(r.ingresos_totales)}</b></div></div><div class="grid"><article class="panel"><h2>Mapa de espacios</h2><div id="parking" class="parking-grid"></div></article><article class="panel"><h2>Estadías activas</h2>${table(['ID', 'Placa', 'Ubicación', 'Entrada'], d.estadias_activas.map(x => `<tr><td>#${x.estadia_id}</td><td>${escape(x.placa)}</td><td>${escape(x.zona)} · ${escape(x.espacio)}</td><td>${date(x.fecha_entrada)}</td></tr>`))}</article></div><div class="grid"><article class="panel"><h2>Últimas estadías</h2>${table(['Cliente', 'Placa', 'Estado', 'Total'], d.ultimas_estadias.map(x => `<tr><td>${escape(x.cliente)}</td><td>${escape(x.placa)}</td><td>${badge(x.estado)}</td><td>${money(x.total)}</td></tr>`))}</article><article class="panel"><h2>Últimos pagos</h2>${table(['Estadía', 'Método', 'Monto'], d.ultimos_pagos.map(x => `<tr><td>#${x.estadia_id}</td><td>${escape(x.metodo_pago)}</td><td>${money(x.monto)}</td></tr>`))}</article></div>`; const spaces = await get('/espacios'); document.querySelector('#parking').innerHTML = spaces.map(s => `<div class="spot ${s.estado.toLowerCase()}"><strong>${escape(s.codigo)}</strong><small>${escape(s.zona)} · ${escape(s.tipo_vehiculo)}</small><small>${badge(s.estado)}</small></div>`).join(''); }
function entrada() { content.innerHTML = `<form class="form-card" id="entryForm"><h2>Registrar entrada</h2><p>La operación es procesada por la función almacenada <code>registrar_entrada</code> de PostgreSQL.</p><label>Placa del vehículo</label><input name="placa" maxlength="15" placeholder="Ej. HAA-1023" required><label>Código del espacio</label><input name="codigo_espacio" maxlength="10" placeholder="Ej. A-01" required><label>Usuario operador</label><input name="nombre_usuario" placeholder="Ej. operador1" required><button class="submit">Registrar entrada</button></form>`; document.querySelector('#entryForm').onsubmit = submitForm('/entrada', data => `Entrada registrada. Estadía #${data.estadia_id} creada correctamente.`); }
async function salida() { const estadias = await get('/estadias'); const activas = estadias.filter(e => e.estado === 'ACTIVA'); content.innerHTML = `<form class="form-card" id="exitForm"><h2>Registrar salida</h2><p>El cálculo del cobro se realiza exclusivamente mediante <code>registrar_salida</code> en PostgreSQL.</p><label>Estadía activa</label><select name="estadia_id" required><option value="">Seleccione una estadía</option>${activas.map(e => `<option value="${e.estadia_id}">#${e.estadia_id} — ${escape(e.placa)} · ${escape(e.espacio)}</option>`).join('')}</select><label>Método de pago</label><select name="metodo_pago" required><option value="">Seleccione un método</option><option>Efectivo</option><option>Tarjeta</option><option>Transferencia</option></select><button class="submit">Registrar salida y pago</button></form>`; document.querySelector('#exitForm').onsubmit = submitForm('/salida', data => `Estadía #${data.estadia_id} finalizada. Total pagado: ${money(data.total)} mediante ${data.metodo_pago}.`); }
function submitForm(path, message) { return async event => { event.preventDefault(); const button = event.target.querySelector('button'); button.disabled = true; try { const body = Object.fromEntries(new FormData(event.target)); const response = await fetch(`${API}${path}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'No se pudo completar la operación.'); notice(message(data)); event.target.reset(); } catch (error) { notice(error.message, 'error'); } finally { button.disabled = false; } }; }
async function listView(type, path, headers, render) { const rows = await get(path); content.innerHTML = `<article class="panel"><h2>${titles[type]}</h2>${table(headers, rows.map(render))}</article>`; }
async function reportes() { const reports = await Promise.all([get('/reportes/ocupacion'), get('/reportes/ingresos'), get('/reportes/ingresos-metodo'), get('/reportes/vehiculos-tipo'), get('/reportes/estadias-estado'), get('/reportes/ingresos-fecha')]); const [o, i, im, vt, ee, f] = reports; const single = (title, data) => `<article class="panel"><h2>${title}</h2>${table(Object.keys(data[0] || {}), data.map(row => `<tr>${Object.values(row).map(v => `<td>${escape(v)}</td>`).join('')}</tr>`))}</article>`; content.innerHTML = `<div class="report-grid">${single('A. Ocupación', o)}${single('B. Ingresos', i)}${single('C. Ingresos por método', im)}${single('D. Vehículos por tipo', vt)}${single('E. Estadías por estado', ee)}${single('F. Ingresos por fecha', f)}</div><article class="panel" style="margin-top:18px"><h2>G. Historial completo de estadías (JOIN)</h2><p class="empty">Consulte la sección Estadías para visualizar el historial construido con JOIN entre estadías, vehículos, clientes, tipos de vehículo, espacios y zonas.</p></article>`; }
const views = { dashboard, entrada, salida, espacios: () => listView('espacios', '/espacios', ['Código', 'Zona', 'Tipo de vehículo', 'Estado'], x => `<tr><td><b>${escape(x.codigo)}</b></td><td>${escape(x.zona)}</td><td>${escape(x.tipo_vehiculo)}</td><td>${badge(x.estado)}</td></tr>`), estadias: () => listView('estadias', '/estadias', ['ID', 'Cliente / Placa', 'Ubicación', 'Entrada', 'Salida', 'Duración', 'Total', 'Estado'], x => `<tr><td>#${x.estadia_id}</td><td>${escape(x.cliente)}<br><small>${escape(x.placa)} · ${escape(x.tipo_vehiculo)}</small></td><td>${escape(x.zona)} · ${escape(x.espacio)}</td><td>${date(x.fecha_entrada)}</td><td>${date(x.fecha_salida)}</td><td>${x.duracion_minutos ?? '—'} min</td><td>${money(x.total)}</td><td>${badge(x.estado)}</td></tr>`), clientes: () => listView('clientes', '/clientes', ['Nombre', 'Teléfono', 'Correo', 'Registro'], x => `<tr><td>${escape(x.nombre)} ${escape(x.apellido)}</td><td>${escape(x.telefono)}</td><td>${escape(x.correo)}</td><td>${date(x.fecha_registro)}</td></tr>`), vehiculos: () => listView('vehiculos', '/vehiculos', ['Placa', 'Cliente', 'Tipo', 'Marca / modelo', 'Año'], x => `<tr><td><b>${escape(x.placa)}</b></td><td>${escape(x.cliente)}</td><td>${escape(x.tipo_vehiculo)}</td><td>${escape(x.marca)} ${escape(x.modelo)}</td><td>${escape(x.anio)}</td></tr>`), pagos: () => listView('pagos', '/pagos', ['Pago', 'Estadía', 'Método', 'Monto', 'Fecha'], x => `<tr><td>#${x.pago_id}</td><td>#${x.estadia_id}</td><td>${escape(x.metodo_pago)}</td><td>${money(x.monto)}</td><td>${date(x.fecha_pago)}</td></tr>`), reportes };
async function show(view) { document.querySelector('#title').textContent = titles[view]; document.querySelector('#notice').style.display = 'none'; content.innerHTML = '<p class="empty">Cargando información desde PostgreSQL…</p>'; try { await views[view](); } catch (error) { content.innerHTML = `<article class="panel"><h2>No fue posible cargar los datos</h2><p class="empty">${escape(error.message)}. Verifique que el backend y PostgreSQL estén en ejecución.</p></article>`; } }
document.querySelectorAll('#nav button').forEach(button => button.addEventListener('click', () => { document.querySelector('#nav .active').classList.remove('active'); button.classList.add('active'); show(button.dataset.view); }));
show('dashboard');
