import { Router } from 'express';
import pool from '../config/database.js';
const router = Router();
const required = value => typeof value === 'string' && value.trim();
router.get('/', async (_req, res, next) => { try { const { rows } = await pool.query('SELECT cliente_id, nombre, apellido, telefono, correo, fecha_registro FROM clientes ORDER BY apellido, nombre'); res.json(rows); } catch (error) { next(error); } });
router.get('/:id', async (req, res, next) => { try { const { rows } = await pool.query(`SELECT c.*, COALESCE(json_agg(json_build_object('vehiculo_id', v.vehiculo_id, 'placa', v.placa, 'marca', v.marca, 'modelo', v.modelo) ORDER BY v.placa) FILTER (WHERE v.vehiculo_id IS NOT NULL), '[]') AS vehiculos FROM clientes c LEFT JOIN vehiculos v ON v.cliente_id = c.cliente_id WHERE c.cliente_id = $1 GROUP BY c.cliente_id`, [req.params.id]); if (!rows[0]) return res.status(404).json({ error: 'El cliente no existe.' }); res.json(rows[0]); } catch (error) { next(error); } });
router.post('/', async (req, res, next) => { const { nombre, apellido, telefono, correo } = req.body; if (!required(nombre) || !required(apellido)) return res.status(400).json({ error: 'Nombre y apellido son obligatorios.' }); try { const { rows } = await pool.query('INSERT INTO clientes (nombre, apellido, telefono, correo) VALUES ($1, $2, $3, $4) RETURNING *', [nombre.trim(), apellido.trim(), telefono?.trim() || null, correo?.trim() || null]); res.status(201).json(rows[0]); } catch (error) { next(error); } });
router.put('/:id', async (req, res, next) => { const { nombre, apellido, telefono, correo } = req.body; if (!required(nombre) || !required(apellido)) return res.status(400).json({ error: 'Nombre y apellido son obligatorios.' }); try { const { rows } = await pool.query('UPDATE clientes SET nombre=$1, apellido=$2, telefono=$3, correo=$4 WHERE cliente_id=$5 RETURNING *', [nombre.trim(), apellido.trim(), telefono?.trim() || null, correo?.trim() || null, req.params.id]); if (!rows[0]) return res.status(404).json({ error: 'El cliente no existe.' }); res.json(rows[0]); } catch (error) { next(error); } });
export default router;
