import { Router } from 'express';
import pool from '../config/database.js';
const router = Router();
const historial = `SELECT e.estadia_id, e.vehiculo_id, COALESCE(c.nombre || ' ' || c.apellido, 'Sin cliente') AS cliente, v.placa, tv.nombre AS tipo_vehiculo, z.nombre AS zona, s.codigo AS espacio, e.fecha_entrada, e.fecha_salida, e.duracion_minutos, t.precio_hora, e.total, e.estado, u.nombre_completo AS operador FROM estadias e JOIN vehiculos v ON v.vehiculo_id = e.vehiculo_id LEFT JOIN clientes c ON c.cliente_id = v.cliente_id JOIN tipos_vehiculo tv ON tv.tipo_vehiculo_id = v.tipo_vehiculo_id JOIN espacios s ON s.espacio_id = e.espacio_id JOIN zonas z ON z.zona_id = s.zona_id JOIN tarifas t ON t.tarifa_id = e.tarifa_id JOIN usuarios u ON u.usuario_id = e.usuario_id`;
router.get('/', async (req, res, next) => { try { const values=[]; let where=''; const add=(sql, value)=> { values.push(value); where += `${where ? ' AND' : ' WHERE'} ${sql.replace('?', `$${values.length}`)}`; }; if (req.query.periodo === 'hoy') add('e.fecha_entrada::date = CURRENT_DATE'); else if (req.query.periodo === 'ayer') add('e.fecha_entrada::date = CURRENT_DATE - 1'); else if (req.query.fecha) add('e.fecha_entrada::date = ?', req.query.fecha); else { if(req.query.desde) add('e.fecha_entrada::date >= ?', req.query.desde); if(req.query.hasta) add('e.fecha_entrada::date <= ?', req.query.hasta); } const { rows } = await pool.query(`${historial}${where} ORDER BY e.fecha_entrada DESC`, values); res.json(rows); } catch (error) { next(error); } });
router.get('/activas', async (_req, res, next) => { try { const { rows } = await pool.query(`${historial} WHERE e.estado='ACTIVA' ORDER BY e.fecha_entrada DESC`); res.json(rows); } catch (error) { next(error); } });
router.post('/entrada', async (req, res, next) => { const { placa, codigo_espacio, nombre_usuario } = req.body; if (![placa, codigo_espacio, nombre_usuario].every(v => typeof v === 'string' && v.trim())) return res.status(400).json({ error: 'Vehículo, espacio y usuario son obligatorios.' }); try { const { rows } = await pool.query('SELECT registrar_entrada($1, $2, $3) AS estadia_id', [placa.trim(), codigo_espacio.trim(), nombre_usuario.trim()]); const ticket = await pool.query(`${historial} WHERE e.estadia_id=$1`, [rows[0].estadia_id]); res.status(201).json({ message: 'Entrada registrada correctamente.', ...ticket.rows[0] }); } catch (error) { next(error); } });
router.post('/salida', async (req, res, next) => { const { estadia_id, metodo_pago } = req.body; if (!Number.isInteger(Number(estadia_id)) || !metodo_pago?.trim()) return res.status(400).json({ error: 'Seleccione una estadía activa y un método de pago.' }); try { await pool.query('SELECT registrar_salida($1, $2) AS total', [Number(estadia_id), metodo_pago.trim()]); const ticket = await pool.query(`${historial} WHERE e.estadia_id=$1`, [Number(estadia_id)]); res.json({ message: 'Salida registrada correctamente.', metodo_pago: metodo_pago.trim(), ...ticket.rows[0] }); } catch (error) { next(error); } });
export default router;
